version: '3.8'
services:
  app:
    build: .
    tty: true
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./:/home/echo-crud
    command:
      - air
  db:
    build: ./database/
    tty: true
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: echo-crud
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: crud
      MYSQL_PASSWORD: crud1234
      MYSQL_PORT: 3306
      TZ: 'Asia/Tokyo'
volumes:
  db-data: