version: '3.8'
services:
  app:
    build: .
    tty: true
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./:/home/echo-crud
    command:
      - air
  db:
    build: ./database/
    tty: true
    restart: always
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./database/ddl/:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      TZ: ${TX}
volumes:
  db-data: